apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv-thetorre-local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /var/lib/thetorre-local/postgresql
