apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kong-chart.fullname" . }}
  labels:
    {{- include "kong-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kong-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kong-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: kong
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: KONG_DATABASE
          value: postgres
        - name: KONG_PG_HOST
          value: {{ .Values.postgresql.host }}
        - name: KONG_PG_PORT
          value: {{ .Values.postgresql.port | quote }}
        - name: KONG_PG_DATABASE
          value: {{ .Values.postgresql.database }}
        - name: KONG_PG_USER
          value: {{ .Values.postgresql.username }}
        - name: KONG_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "kong-chart.fullname" . }}-secret
              key: postgresql-password
        - name: KONG_PROXY_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_ADMIN_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_PROXY_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_LISTEN
          value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
        - name: KONG_PROXY_LISTEN
          value: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
        ports:
        - name: proxy
          containerPort: 8000
          protocol: TCP
        - name: proxy-ssl
          containerPort: 8443
          protocol: TCP
        - name: admin
          containerPort: 8001
          protocol: TCP
        - name: admin-ssl
          containerPort: 8444
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /status
            port: 8001
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: /status
            port: 8001
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
