apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kong-chart.fullname" . }}-secret
  labels:
    {{- include "kong-chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
type: Opaque
stringData:
  postgresql-password: {{ .Values.postgresql.password | quote }}
