apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak-chart.fullname" . }}-secret
  labels:
    {{- include "keycloak-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.auth.adminPassword | quote }}
  postgresql-password: {{ .Values.postgresql.password | quote }}
