apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plant-management-chart.fullname" . }}
  labels:
    {{- include "plant-management-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.secrets.dbPassword | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  umbrella-api-key: {{ .Values.secrets.umbrellaApiKey | quote }}
